### ISSUE TITLE
Implement - Interactable - Ramp

### ISSUE THREAD

**Issue by jakobfree** [salohins/CyberBiker#14]
- Player gets airtime by driving over the ramp

Variables

- [ ] Launch height
- [ ] Launch distance
- [ ] Launch speed

**Comment by salohins** [comment]
the ramp can be removed. You need to find city biome prefab Assets/Level/Prefabs/WorldGenerator/CityBiome. You can change the size of Tiles array or just remove RoadRampCombined prefab 



![Image](https://github.com/salohins/CyberBiker/assets/58812141/9444959d-a51b-4312-b9f9-f4469fcc97f9)

**Comment by salohins** [comment]
at the moment there are no variables attached to the ramp. Launch height and distance can be regulated by changing the gravity of the game

**Comment by jakobfree** [comment]
I'll close this out.
