### ISSUE TITLE
Implement - Traffic 001

### ISSUE THREAD

**Issue by jakobfree** [salohins/CyberBiker#21]
- Cars need to travel toward player
- Cars inflict damage if player comes into contact with them

Variables

- [ ] Traffic density
- [ ] Traffic speed (range)

**Comment by salohins** [comment]
the speed of the cars can be regulated inside car prefab settings 


![Image](https://github.com/salohins/CyberBiker/assets/58812141/caf2158e-6137-4f6c-bfcc-1b963deaa329)

**Comment by jakobfree** [comment]
Let's talk about the reasoning behind controlling speed on a car-by-car basis vs other options.
