### ISSUE TITLE
Implement - Curve Editor for Challenge/Progression

### ISSUE THREAD

**Issue by jakobfree** [salohins/CyberBiker#33]

**Comment by salohins** [comment]
At the moment difficulty level is not attached to any variable. Meaning there won't be any changes with level progression. You can just check if the level changes correctly according to the curve

**Comment by salohins** [comment]
Important. Do not change time value in the curve

**Comment by jakobfree** [comment]
Let's talk about this live. Not really sure what I should be looking for in terms of the changes. Furthermore, hard to test because the traffic generation makes has way too much density.
