### ISSUE TITLE
75 Percent Rule for lateral traffic placement

### ISSUE THREAD

**Issue by jakobfree** [salohins/CyberBiker#38]
Cars always need to allow for at least one "safe passage" through traffic. In the example we discussed, if there are four lanes, at least one of them always needs to be open.

**Comment by salohins** [comment]
I couldn't really figure out how to implement that rule. So instead I increased intervals between cars and added two variables (car min speed and car max speed). For now, everything works fine, I've never had a situation where 4 cars block the road.
